Updated information for Game Options
openupm/openupm pull request #1798
Opened 2021-01-12 15:55 UTC by peeweek

2021-01-12 16:13 UTC, favoyang submitted a review, later dismissed

2021-01-12 16:20 UTC, favoyang requested changes
- Please change "GUI" to lowercase ("gui"), you can find all topic slugs in [data/topics.yml](https://github.com/openupm/openupm/blob/master/data/topics.yml).
- Please change hunter back to "JesseTG". He is the first user who submits the package to OpenUPM. You as the package owner will be presented on the package card and the package detail page as well.

2021-01-13 03:13 UTC, favoyang commented
@peeweek Please checkout this comment https://github.com/openupm/openupm/pull/1798#pullrequestreview-566442074

2021-01-13 06:53 UTC, peeweek commented
ok thanks for all the precision 
I was not sure about the hunter field.

2021-01-13 06:59 UTC, favoyang approved these changes

2021-01-13 06:59 UTC, merged